### ISSUE TITLE
buffer content is not the same as ansible-doc output

### ISSUE THREAD

**Issue by Geertsky** [mfussenegger/nvim-ansible#5]
Hello Mathias
Danke vielmals für dein Plugin!

But it doesn't seem to work as I would like...
I have a playbook opened, the filetype is set to yaml.ansible, and when I press `K` a window opens with the output of ansible-doc.
Thing is that the ansible-doc output is only shown for the first page. When I call ansible-doc directly it is opened in a pager. So I guess the problem lies there, but I can't seem to find where I can disable this pager.
Do you have any idea?

Thanks!

**Comment by mfussenegger** [comment]
It should use the keywordprg and open a split terminal with the ansible-doc output:


![recording](https://github.com/mfussenegger/nvim-ansible/assets/38700/121afd91-0915-44dc-b7b8-83f799b85fe8)


If it doesn't, you probably mapped `K` to `vim.lsp.buf.hover()` which shows the result from the language server.

**Comment by Geertsky** [comment]
That looks great! 
You are right that there was a maping to `vim.lsp.buf.hover()`. I've commented this line in `init.lua`, confirmed the maping does no longer exist, confirmed `keywordprg=:sp tem://ansible-doc` but it still opens the same one page only of `ansible-doc`.

Do you have any clue?

**Comment by Geertsky** [comment]
added `vim.env.PAGER = 'cat'` to `init.lua`
