### ISSUE TITLE
Enhanced syntax support

### ISSUE THREAD

**Issue by goetzc** [mfussenegger/nvim-ansible#6]
Hey, any toughs about enhancing YAML syntax with Ansible keywords support? Such as:
 
https://github.com/pearofducks/ansible-vim/blob/afc739e505053a6143a1fc6cedac6fb4d7a1d4db/syntax/ansible.vim

**Comment by mfussenegger** [comment]
Currently I've no plans to add that. If you're using https://github.com/ansible/ansible-language-server you already get additional syntax highlighting via semantic tokens.
